ui:
  title: "Мероприятия Культурного центра"
  icon: "classpath:com/vladislav/application/icon.png"
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: "jdbc:sqlite:src/main/resources/com/vladislav/infrastructure/db.db"